export { default as Header } from './Header'
export { default as Main } from './Main'
export { default as Result } from './Result'
export { default as InputForm } from './InputForm'
export { default as AttributesResctrictionForm } from './AttributesResctrictionForm'
export { default as ProductRestrictionForm} from './ProductRestrictionForm'